<?php

/**
 * Testi dell'interfaccia della pagina del team. I contenuti (frasi, bio,
 * curiosita') arrivano dal database; qui ci sono solo etichette e messaggi.
 */

function esports_strings(string $lang): array
{
    $strings = [
        'it' => [
            'lineup' => 'Line-up',
            'bench' => 'Panchina e staff',
            'palmares' => 'Palmarès',
            'former' => 'Ex player',
            'hidden_group' => 'Nascosti: li vede solo lo staff',
            'hidden_badge' => 'Nascosto',
            'preview_banner' => 'Anteprima: questo player è nascosto, lo vede solo lo staff.',
            'empty_title' => 'La line-up sta arrivando',
            'empty_text' => 'Stiamo ancora decidendo chi mandare a morire per primo.',
            'soon_title' => 'Il team sta arrivando',
            'soon_text' => 'Questa sezione non è ancora pronta. Torna a trovarci presto!',
            'go_home' => 'Torna alla home',
            'not_found_title' => 'Player non trovato',
            'not_found_text' => 'Questo player non esiste o non fa più parte del team.',
            'back_to_team' => 'Torna al team',
            'open_player' => 'Apri la pagina di %s',
            'other_players' => 'Altri player',
            'close' => 'Chiudi',
            'prev' => 'Player precedente',
            'next' => 'Player successivo',
            'prev_short' => 'Precedente',
            'next_short' => 'Successivo',
            'stats' => 'Statistiche',
            'setup' => 'Setup',
            'crosshair' => 'Codice mirino',
            'copy' => 'Copia',
            'copied' => 'Codice copiato!',
            'copy_failed' => 'Copia non riuscita',
            'facts' => 'Curiosità',
            'bio' => 'Chi è',
            'clips' => 'Clip',
            'socials' => 'Social',
            'profile_link' => 'Profilo su Cripsum',
            'music_kit' => 'Music kit',
            'music_play' => 'Fai partire la musica',
            'music_pause' => 'Metti in pausa la musica',
            'music_volume' => 'Volume della musica',
            'music_blocked' => 'Tocca un punto qualsiasi per far partire la musica',
            'music_tap' => 'Tocca per ascoltare la musica',
            'music_error' => 'Brano non disponibile',
            'level' => 'Livello %d',
            'rating_premier' => 'Premier rating',
            'rating_faceit' => 'FACEIT',
            'player_fallback_desc' => '%s, %s del %s.',
            'swipe_hint' => 'Scorri per cambiare player',
        ],
        'en' => [
            'lineup' => 'Line-up',
            'bench' => 'Bench & staff',
            'palmares' => 'Honours',
            'former' => 'Former players',
            'hidden_group' => 'Hidden: staff only',
            'hidden_badge' => 'Hidden',
            'preview_banner' => 'Preview: this player is hidden, only staff can see it.',
            'empty_title' => 'The line-up is on its way',
            'empty_text' => 'We\'re still deciding who gets sent to die first.',
            'soon_title' => 'The team is on its way',
            'soon_text' => 'This section isn\'t ready yet. Come back soon!',
            'go_home' => 'Back to home',
            'not_found_title' => 'Player not found',
            'not_found_text' => 'This player doesn\'t exist or is no longer part of the team.',
            'back_to_team' => 'Back to the team',
            'open_player' => 'Open %s\'s page',
            'other_players' => 'Other players',
            'close' => 'Close',
            'prev' => 'Previous player',
            'next' => 'Next player',
            'prev_short' => 'Previous',
            'next_short' => 'Next',
            'stats' => 'Stats',
            'setup' => 'Setup',
            'crosshair' => 'Crosshair code',
            'copy' => 'Copy',
            'copied' => 'Code copied!',
            'copy_failed' => 'Copy failed',
            'facts' => 'Fun facts',
            'bio' => 'About',
            'clips' => 'Clips',
            'socials' => 'Socials',
            'profile_link' => 'Cripsum profile',
            'music_kit' => 'Music kit',
            'music_play' => 'Play the music',
            'music_pause' => 'Pause the music',
            'music_volume' => 'Music volume',
            'music_blocked' => 'Tap anywhere to start the music',
            'music_tap' => 'Tap to play the music',
            'music_error' => 'Track unavailable',
            'level' => 'Level %d',
            'rating_premier' => 'Premier rating',
            'rating_faceit' => 'FACEIT',
            'player_fallback_desc' => '%s, %s of %s.',
            'swipe_hint' => 'Swipe to change player',
        ],
    ];

    return $strings[$lang] ?? $strings['it'];
}
