window.rarities = [
    { name: "ABDUL LO SCHIAVO", rarity: "comune", img: "abdul.jpg", audio: "ndinero.mp3", category: "meme" },
    { name: "XALX ANDREA", rarity: "epico", img: "cavallo.jpg", audio: "2KE, 808iuli - X-SLIDE.mp3", category: "discordArc" },
    { name: "OLD CHINESE SAGE", rarity: "leggendario", img: "chinese-essay-2.jpg", audio: "Jin-Sheng-Yuan.mp3", category: "meme" },
    { name: "CRIPSUM", rarity: "speciale", img: "cripsumchisiamo.jpg", audio: "phonksburro13.mp3", category: "king" },
    { name: "SIMONE TUSSI", rarity: "leggendario", img: "slott8.jpg", audio: "apocalypse.mp3", category: "5CINF" },
    { name: "SAMARPREET", rarity: "leggendario", img: "samarpreet.jpg", audio: "ilikeyouso.mp3", category: "5CINF" },
    { name: "BARANDEEP", rarity: "raro", img: "barandeep.jpg", audio: "punjabimc.mp3", category: "5CINF" },
    { name: "JAY", rarity: "raro", img: "jayquadrato.png", audio: "ninjagosigla.mp3", category: "meme" },
    { name: "RAY (trader)", rarity: "epico", img: "ray.jpg", audio: "maozedong.mp3", category: "5CINF" },
    { name: "PICCOLO TOP 1", rarity: "leggendario", img: "photo_2023-11-14_17-21-10.jpg", audio: "mikumiku.mp3", category: "discordArc" },
    { name: "MYCHY", rarity: "raro", img: "mychy.jpg", audio: "mychy.mp3", category: "discordArc" },
    { name: "FNL PAPERA", rarity: "epico", img: "papera.jpg", audio: "phonksburro2.mp3", category: "discordArc" },
    { name: "WRYCHARLES", rarity: "epico", img: "wrycharles1.png", audio: "wry.mp3", category: "meme" },
    { name: "GOKU PELAO", rarity: "comune", img: "gokupelao.jpg", audio: "powler.mp3", category: "meme" },
    { name: "NINO", rarity: "comune", img: "slott9.jpg", audio: "ninoballetto.mp3", category: "meme" },
    { name: "LOLLO LAPULCE", rarity: "comune", img: "slott6.jpg", audio: "clown.mp3", category: "meme" },
    { name: "宝鐘マリン", rarity: "epico", img: "anime.jpg", audio: "musicaanime.mp3", category: "anime" },
    { name: "DANEBI", rarity: "leggendario", img: "sahe.jpg", audio: "nerd.mp3", category: "5CINF" },
    { name: "DON POLLO", rarity: "comune", img: "donpollo.jpg", audio: "donpollo.mp3", category: "meme" },
    { name: "JOHN PORK", rarity: "raro", img: "johnpork.jpg", audio: "johnpork.mp3", category: "meme" },
    { name: "CASEOH", rarity: "comune", img: "caseoh.jpg", audio: "caseoh-shits-himself.mp3", category: "meme" },
    { name: "GIUSEPPE SIMONE", rarity: "comune", img: "giuseppesimone.jpg", audio: "uccello.mp3", category: "meme" },
    { name: "SEI UNA MONELLA", rarity: "epico", img: "seiunamonella.jpg", audio: "monella.mp3", category: "meme" },
    { name: "DUKE DENNIS", rarity: "epico", img: "dukedennis.jpg", audio: "rizz-song.mp3", category: "meme" },
    { name: "QUANDALE DINGLE", rarity: "raro", img: "quandaledingle.jpg", audio: "quandale-dingle.mp3", category: "meme" },
    { name: "ROSARIO MUNIZ", rarity: "comune", img: "muniz.jpg", audio: "muniz.mp3", category: "meme" },
    { name: "WALTER WHITE", rarity: "comune", img: "walterwhite.jpg", audio: "intro-bb.mp3", category: "meme" },
    { name: "HEISENBERG", rarity: "leggendario", img: "heisenberg-prime.jpg", audio: "knocks.mp3", category: "meme" },
    { name: "SQUIDDI", rarity: "raro", img: "squiddi.jpg", audio: "squiddi.mp3", category: "meme" },
    { name: "ZUCCHINO", rarity: "comune", img: "zucchino.jpg", audio: "its-coming-out.mp3", category: "meme" },
    { name: "POPPY (MANI)", rarity: "raro", img: "poppymani.jpg", audio: "meowmeow.mp3", category: "poppy" },
    { name: "POPPY (BISCOTTI)", rarity: "leggendario", img: "poppystelle.jpg", audio: "meowsad.mp3", category: "poppy" },
    { name: "POPPY (CESTINO)", rarity: "speciale", img: "poppycestino.jpg", audio: "meow.mp3", category: "poppy" },
    { name: "DETECTIVE CICCIO", rarity: "leggendario", img: "detectiveciccio.jpg", audio: "detective-ciccio.mp3", category: "meme" },
    { name: "CICCIOGAMER89", rarity: "comune", img: "cicciogamer.jpg", audio: "ciccio-merde.mp3", category: "meme" },
    { name: "FAKESTARS90", rarity: "epico", img: "djstucassum.jpg", audio: "machiecherompeilcazzo.mp3", category: "discordArc" },
    { name: "RISORSE UMANE", rarity: "leggendario", img: "risorse-umane.png", audio: "Elevator Music.mp3", category: "meme" },
    { name: "GINNASTICA", rarity: "speciale", img: "ginnastica.png", audio: "audioduro1.mp3", category: "meme" },
    { name: "CHANEL", rarity: "comune", img: "chanel.jpg", audio: "Elevator Music.mp3", category: "discordArc" },
    { name: "DANIEL", rarity: "epico", img: "daniel.jpg", audio: "rapfrociogay.mp3", category: "5CINF" },
    { name: "COSSU", rarity: "speciale", img: "cossupisnelo.gif", audio: "cossusong.mp3", category: "OG" },
    { name: "SALE MEDIO", rarity: "raro", img: "sale.jpg", audio: "toki.mp3", category: "discordArc" },
    { name: "TOKI", rarity: "epico", img: "toki.jpg", audio: "salemedioaudio.mp3", category: "discordArc" },
    { name: "CRIPSUM (DISOCCUPATO)", rarity: "segreto", img: "shorekeeper-pfp.gif", audio: "acido.mp3", category: "king" }
];
// { name: "", rarity: "", img: ".jpg", audio: ".mp3", category: "" },

window.originalRarities = [...window.rarities];