window.rarities = [
    { name: "ABDUL LO SCHIAVO", rarity: "comune", img: "img/abdul.jpg", audio: "audio/ndinero.mp3", category: "meme" },
    { name: "XALX ANDREA", rarity: "comune", img: "img/cavallo.jpg", audio: "audio/2KE, 808iuli - X-SLIDE.mp3", category: "temp" },
    { name: "OLD CHINESE SAGE", rarity: "mitico", img: "img/chinese-essay-2.jpg", audio: "audio/Jin-Sheng-Yuan.mp3", category: "meme" },
    { name: "CRIPSUM", rarity: "speciale", img: "img/cripsumchisiamo.jpg", audio: "audio/phonksburro13.mp3", category: "king" },
    { name: "SIMONE TUSSI", rarity: "leggendario", img: "img/slott8.jpg", audio: "audio/apocalypse.mp3", category: "5CINF" },
    { name: "SAMARPREET", rarity: "leggendario", img: "img/samarpreet.jpg", audio: "audio/ilikeyouso.mp3", category: "5CINF" },
    { name: "BARANDEEP", rarity: "raro", img: "img/barandeep.jpg", audio: "audio/punjabimc.mp3", category: "5CINF" },
    { name: "JAY", rarity: "raro", img: "img/jayquadrato.png", audio: "audio/ninjagosigla.mp3", category: "meme" },
    { name: "RAY (trader)", rarity: "epico", img: "img/ray.jpg", audio: "audio/maozedong.mp3", category: "5CINF" },
    { name: "PICCOLO TOP 1", rarity: "epico", img: "img/photo_2023-11-14_17-21-10.jpg", audio: "audio/mikumiku.mp3", category: "temp" },
    { name: "MYCHY", rarity: "leggendario", img: "img/mychy.jpg", audio: "audio/mychy.mp3", category: "temp" },
    { name: "FNL PAPERA", rarity: "raro", img: "img/papera.jpg", audio: "audio/phonksburro2.mp3", category: "temp" },
    { name: "WRYCHARLES", rarity: "epico", img: "img/wrycharles1.png", audio: "audio/wry.mp3", category: "meme" },
    { name: "GOKU PELAO", rarity: "comune", img: "img/gokupelao.jpg", audio: "audio/powler.mp3", category: "meme" },
    { name: "NINO", rarity: "comune", img: "img/slott9.jpg", audio: "audio/ninoballetto.mp3", category: "meme" },
    { name: "LOLLO LAPULCE", rarity: "comune", img: "img/slott6.jpg", audio: "audio/clown.mp3", category: "meme" },
    { name: "宝鐘マリン", rarity: "epico", img: "img/anime.jpg", audio: "audio/musicaanime.mp3", category: "anime" },
    { name: "DANEBI", rarity: "mitico", img: "img/sahe.jpg", audio: "audio/nerd.mp3", category: "5CINF" },
    { name: "DON POLLO", rarity: "comune", img: "img/donpollo.jpg", audio: "audio/donpollo.mp3", category: "meme" },
    { name: "JOHN PORK", rarity: "raro", img: "img/johnpork.jpg", audio: "audio/johnpork.mp3", category: "meme" },
    { name: "CASEOH", rarity: "comune", img: "img/caseoh.jpg", audio: "audio/caseoh-shits-himself.mp3", category: "meme" },
    { name: "PLANET CASEOH", rarity: "leggendario", img: "img/planetcaseoh.jpg", audio: "audio/caseohsong.mp3", category: "meme" },
    { name: "GIUSEPPE SIMONE", rarity: "comune", img: "img/giuseppesimone.jpg", audio: "audio/uccello.mp3", category: "meme" },
    { name: "SEI UNA MONELLA", rarity: "epico", img: "img/seiunamonella.jpg", audio: "audio/monella.mp3", category: "meme" },
    { name: "DUKE DENNIS", rarity: "epico", img: "img/dukedennis.jpg", audio: "audio/rizz-song.mp3", category: "meme" },
    { name: "QUANDALE DINGLE", rarity: "raro", img: "img/quandaledingle.jpg", audio: "audio/quandale-dingle.mp3", category: "meme" },
    { name: "ROSARIO MUNIZ", rarity: "comune", img: "img/muniz.jpg", audio: "audio/muniz.mp3", category: "meme" },
    { name: "WALTER WHITE", rarity: "comune", img: "img/walterwhite.jpg", audio: "audio/intro-bb.mp3", category: "meme" },
    { name: "HEISENBERG", rarity: "mitico", img: "img/heisenberg-prime.jpg", audio: "audio/knocks.mp3", category: "meme" },
    { name: "SQUIDDI", rarity: "raro", img: "img/squiddi.jpg", audio: "audio/squiddi.mp3", category: "meme" },
    { name: "ZUCCHINO", rarity: "comune", img: "img/zucchino.jpg", audio: "audio/its-coming-out.mp3", category: "meme" },
    { name: "POPPY (MANI)", rarity: "raro", img: "img/poppymani.jpg", audio: "audio/meowmeow.mp3", category: "poppy" },
    { name: "POPPY (BISCOTTI)", rarity: "leggendario", img: "img/poppystelle.jpg", audio: "audio/meowsad.mp3", category: "poppy" },
    { name: "POPPY (CESTINO)", rarity: "speciale", img: "img/poppycestino.jpg", audio: "audio/meow.mp3", category: "poppy" },
    { name: "DETECTIVE CICCIO", rarity: "leggendario", img: "img/detectiveciccio.jpg", audio: "audio/detective-ciccio.mp3", category: "meme" },
    { name: "CICCIOGAMER89", rarity: "comune", img: "img/cicciogamer.jpg", audio: "audio/ciccio-merde.mp3", category: "meme" },
    { name: "GASTA", rarity: "mitico", img: "img/gasta.png", audio: "audio/gasta.mp3", category: "5CINF" },
    { name: "FAKESTARS90", rarity: "raro", img: "img/djstucassum.jpg", audio: "audio/machiecherompeilcazzo.mp3", category: "temp" },
    { name: "RISORSE UMANE", rarity: "leggendario", img: "img/risorse-umane.png", audio: "audio/Elevator Music.mp3", category: "meme" },
    { name: "GINNASTICA", rarity: "speciale", img: "img/ginnastica.png", audio: "audio/audioduro1.mp3", category: "meme" },
    { name: "CHANEL", rarity: "comune", img: "img/chanel.jpg", audio: "audio/Elevator Music.mp3", category: "temp" },
    { name: "DANIEL", rarity: "epico", img: "img/daniel.jpg", audio: "audio/rapfrociogay.mp3", category: "5CINF" }
];
// { name: "", rarity: "", img: "img/.jpg", audio: "audio/.mp3", category: "" },

window.originalRarities = [...window.rarities];