<?php

/**
 * Testi dell'interfaccia di Edits. Titolo e sottotitolo arrivano dal
 * pannello (shop_pagine); titoli e musiche degli edit dal database.
 */

function edits_strings(string $lang): array
{
    $strings = [
        'it' => [
            'page_title' => 'Edits',
            'meta_description' => 'Gli edit di Cripsum™: anime, giochi, influencer e meme.',
            'title' => 'I miei edit',
            'subtitle' => 'Una raccolta dei miei edit. Aprine uno, scorri con le frecce e condividi il link con chi vuoi.',
            'watch_latest' => "Guarda l'ultimo",
            'featured' => 'In evidenza',
            'new' => 'Nuovo',
            'seen' => 'Visto',
            'all' => 'Tutti',
            'categories' => 'Categorie',
            'search' => 'Cerca per nome o musica...',
            'search_label' => 'Cerca un edit',
            'sort' => 'Ordina',
            'sort_recent' => 'Più recenti',
            'sort_popular' => 'Più visti',
            'sort_name' => 'Nome (A-Z)',
            'hide_seen' => 'Nascondi già visti',
            'empty_title' => 'Nessun edit trovato',
            'empty_text' => 'Prova a cambiare filtro o ricerca.',
            'reset' => 'Mostra tutti',
            'watch' => 'Guarda %s',
            'collab_with' => 'collab con %s',
            'music' => 'Musica',
            'copy_link' => 'Copia link',
            'copied' => 'Link copiato',
            'copy_failed' => 'Non sono riuscito a copiare il link',
            'watch_on' => 'Guardalo su %s',
            'watch_post' => 'Guarda il post originale',
            'prev' => 'Precedente',
            'next' => 'Successivo',
            'close' => 'Chiudi',
            'missing_title' => 'Video non disponibile',
            'missing_text' => 'Questo edit non si può guardare qui al momento.',
            'soon_title' => 'Pagina in aggiornamento',
            'soon_text' => 'Stiamo sistemando questa pagina. Torna a trovarci tra poco!',
            'none_title' => 'Gli edit stanno arrivando',
            'none_text' => 'Qui non c\'è ancora niente da guardare.',
            'go_home' => 'Torna alla home',
            'not_found' => 'Questo edit non esiste più: eccoti gli altri.',
        ],
        'en' => [
            'page_title' => 'Edits',
            'meta_description' => 'Cripsum™ edits: anime, games, influencers and memes.',
            'title' => 'My latest edits',
            'subtitle' => 'A collection of my edits. Open one, flip through with the arrows and share the link with anyone.',
            'watch_latest' => 'Watch the latest',
            'featured' => 'Featured',
            'new' => 'New',
            'seen' => 'Watched',
            'all' => 'All',
            'categories' => 'Categories',
            'search' => 'Search by name or music...',
            'search_label' => 'Search an edit',
            'sort' => 'Sort',
            'sort_recent' => 'Most recent',
            'sort_popular' => 'Most watched',
            'sort_name' => 'Name (A-Z)',
            'hide_seen' => 'Hide watched',
            'empty_title' => 'No edits found',
            'empty_text' => 'Try another filter or search.',
            'reset' => 'Show all',
            'watch' => 'Watch %s',
            'collab_with' => 'collab with %s',
            'music' => 'Music',
            'copy_link' => 'Copy link',
            'copied' => 'Link copied',
            'copy_failed' => "Couldn't copy the link",
            'watch_on' => 'Watch it on %s',
            'watch_post' => 'Watch the original post',
            'prev' => 'Previous',
            'next' => 'Next',
            'close' => 'Close',
            'missing_title' => 'Video unavailable',
            'missing_text' => "This edit can't be watched here right now.",
            'soon_title' => 'Page being updated',
            'soon_text' => "We're fixing up this page. Check back soon!",
            'none_title' => 'Edits are on their way',
            'none_text' => 'Nothing to watch here yet.',
            'go_home' => 'Back to home',
            'not_found' => 'This edit is gone: here are the others.',
        ],
    ];

    return $strings[$lang] ?? $strings['it'];
}
