<?php

/**
 * Testi dell'interfaccia di Chi siamo e della candidatura. Titoli e testi
 * della pagina arrivano dal pannello (shop_pagine); questi sono le
 * etichette e i testi di scorta.
 */

function chisiamo_strings(string $lang): array
{
    $strings = [
        'it' => [
            'page_title' => 'Chi siamo',
            'meta_description' => 'Il team di Cripsum™: editor, developer e gente strana che manda avanti il sito.',
            'title' => 'Il nostro team di sviluppo',
            'subtitle' => 'Editor, developer e gente strana: ecco chi manda avanti Cripsum™. Vuoi entrare anche tu? Manda la tua candidatura.',
            'apply' => 'Candidati',
            'meet_team' => 'Conosci il team',
            'join_title' => 'Unisciti al Team!',
            'join_text' => 'Hai quello che serve per far parte della squadra più king del web? Mandaci la tua candidatura.',
            'join_button' => 'Invia la tua candidatura',
            'profile' => 'Profilo',
            'profile_of' => 'Profilo di %s',
            'premium' => 'Premium',
            'social_of' => '%s di %s',
            'team_label' => 'Il team',
            'empty_title' => 'Il team sta arrivando',
            'empty_text' => 'Stiamo ancora decidendo chi mettere in vetrina.',
            'soon_title' => 'Pagina in aggiornamento',
            'soon_text' => 'Stiamo sistemando questa pagina. Torna a trovarci tra poco!',
            'go_home' => 'Torna alla home',
            // Candidatura
            'apply_title' => 'Candidatura',
            'apply_intro' => 'Manda i dati per apparire nella pagina Chi siamo. Ti rispondiamo nella posta del sito.',
            'apply_login' => 'Per poter mandare la tua candidatura devi avere un account Cripsum™',
            'apply_name' => 'Nome sulla card',
            'apply_description' => 'Descrizione',
            'apply_description_hint' => 'Breve e leggibile, in stile pagina Chi siamo.',
            'apply_description_placeholder' => 'Scrivi due righe su di te',
            'apply_photo' => 'Foto',
            'apply_photo_hint' => 'JPG, PNG o WebP, al massimo 5 MB. Meglio quadrata.',
            'apply_social_name' => 'Username social',
            'apply_social_link' => 'Link social',
            'optional' => 'Facoltativo',
            'apply_send' => 'Invia candidatura',
            'apply_sending' => 'Invio candidatura...',
            'apply_back' => 'Torna a Chi siamo',
            'apply_ok' => 'Candidatura inviata! Ti rispondiamo nella posta del sito.',
            'apply_pending' => 'Hai già una candidatura in attesa: ti rispondiamo nella posta del sito appena la guardiamo.',
            'apply_err_name' => 'Scrivi il nome da mostrare sulla card (al massimo 60 caratteri).',
            'apply_err_description' => 'Scrivi una descrizione (al massimo 700 caratteri).',
            'apply_err_link' => 'Il link social deve essere un indirizzo https completo.',
            'apply_err_photo_missing' => 'Carica una foto.',
            'apply_err_photo_too_big' => 'La foto supera i 5 MB.',
            'apply_err_photo_type' => 'La foto deve essere JPG, PNG o WebP.',
            'apply_err_server' => 'Non siamo riusciti a salvare la candidatura. Riprova tra poco.',
            'apply_err_closed' => 'Le candidature non sono ancora aperte. Riprova tra poco.',
            'apply_err_csrf' => 'Sessione scaduta: ricarica la pagina e riprova.',
        ],
        'en' => [
            'page_title' => 'About us',
            'meta_description' => 'The Cripsum™ team: editors, developers and weird people keeping the site alive.',
            'title' => 'Our development team',
            'subtitle' => 'Editors, developers and weird people: meet the crew behind Cripsum™. Want in? Send us your application.',
            'apply' => 'Apply',
            'meet_team' => 'Meet the team',
            'join_title' => 'Join the Team!',
            'join_text' => 'Do you have what it takes to be part of the coolest squad on the web? Send us your application.',
            'join_button' => 'Send your application',
            'profile' => 'Profile',
            'profile_of' => "%s's profile",
            'premium' => 'Premium',
            'social_of' => "%s's %s",
            'team_label' => 'The team',
            'empty_title' => 'The team is on its way',
            'empty_text' => "We're still picking who goes on display.",
            'soon_title' => 'Page being updated',
            'soon_text' => "We're fixing up this page. Check back soon!",
            'go_home' => 'Back to home',
            'apply_title' => 'Application',
            'apply_intro' => 'Send your details to appear on the About us page. We will answer in your site inbox.',
            'apply_login' => 'You need a Cripsum™ account to send your application',
            'apply_name' => 'Name on the card',
            'apply_description' => 'Description',
            'apply_description_hint' => 'Short and readable, in the style of the About us page.',
            'apply_description_placeholder' => 'Write a couple of lines about yourself',
            'apply_photo' => 'Photo',
            'apply_photo_hint' => 'JPG, PNG or WebP, up to 5 MB. Square works best.',
            'apply_social_name' => 'Social username',
            'apply_social_link' => 'Social link',
            'optional' => 'Optional',
            'apply_send' => 'Send application',
            'apply_sending' => 'Sending application...',
            'apply_back' => 'Back to About us',
            'apply_ok' => 'Application sent! We will answer in your site inbox.',
            'apply_pending' => 'You already have an application waiting: we will answer in your site inbox as soon as we look at it.',
            'apply_err_name' => 'Write the name to show on the card (up to 60 characters).',
            'apply_err_description' => 'Write a description (up to 700 characters).',
            'apply_err_link' => 'The social link must be a full https address.',
            'apply_err_photo_missing' => 'Upload a photo.',
            'apply_err_photo_too_big' => 'The photo is larger than 5 MB.',
            'apply_err_photo_type' => 'The photo must be JPG, PNG or WebP.',
            'apply_err_server' => "We couldn't save your application. Try again in a moment.",
            'apply_err_closed' => 'Applications are not open yet. Try again in a moment.',
            'apply_err_csrf' => 'Session expired: reload the page and try again.',
        ],
    ];

    return $strings[$lang] ?? $strings['it'];
}
