<?php
declare(strict_types=1);

function gd_api_create_match(mysqli $mysqli): void {
    $uid=gd_require_login(); $in=gd_input(); $mode=gd_mode((string)($in['mode']??'casual')); $code=gd_room_code();
    $q=$mysqli->prepare("INSERT INTO game_matches (room_code,status,mode,player1_id,spectator_allowed) VALUES (?,'waiting',?,?,1)");
    if(!$q) gd_fail('Non riesco a creare la partita.',500); $q->bind_param('ssi',$code,$mode,$uid); $q->execute(); $id=$q->insert_id; $q->close(); gd_ok(['match_id'=>$id,'room_code'=>$code]);
}
function gd_api_find_match(mysqli $mysqli): void {
    $uid=gd_require_login(); $mode=gd_mode((string)(gd_input()['mode']??'casual')); $mysqli->begin_transaction();
    try { $q=$mysqli->prepare("SELECT * FROM game_matches WHERE status='waiting' AND mode=? AND player1_id<>? AND player2_id IS NULL ORDER BY created_at ASC LIMIT 1 FOR UPDATE"); if(!$q) throw new Exception('prepare'); $q->bind_param('si',$mode,$uid); $q->execute(); $match=$q->get_result()->fetch_assoc(); $q->close();
        if($match){ $mid=(int)$match['id']; $u=$mysqli->prepare("UPDATE game_matches SET player2_id=?,status='team_select',updated_at=NOW() WHERE id=? AND player2_id IS NULL"); $u->bind_param('ii',$uid,$mid); $u->execute(); $u->close(); $mysqli->commit(); gd_ok(['match_id'=>$mid,'room_code'=>$match['room_code'],'joined'=>true]); }
        $code=gd_room_code(); $i=$mysqli->prepare("INSERT INTO game_matches (room_code,status,mode,player1_id,spectator_allowed) VALUES (?,'waiting',?,?,1)"); $i->bind_param('ssi',$code,$mode,$uid); $i->execute(); $mid=$i->insert_id; $i->close(); $mysqli->commit(); gd_ok(['match_id'=>$mid,'room_code'=>$code,'joined'=>false]);
    } catch(Throwable $e){ $mysqli->rollback(); error_log('gd_find_match: '.$e->getMessage()); gd_fail('Matchmaking fallito.',500); }
}
function gd_api_join_match(mysqli $mysqli): void {
    $uid=gd_require_login(); $code=strtoupper(trim((string)(gd_input()['room_code']??''))); if(!preg_match('/^[A-Z0-9_-]{1,16}$/',$code)) gd_fail('Codice stanza non valido.'); $mysqli->begin_transaction();
    try { $q=$mysqli->prepare('SELECT * FROM game_matches WHERE room_code=? LIMIT 1 FOR UPDATE'); $q->bind_param('s',$code); $q->execute(); $match=$q->get_result()->fetch_assoc(); $q->close(); if(!$match) gd_fail('Partita non trovata.',404); if((int)$match['player1_id']===$uid){$mysqli->commit(); gd_ok(['match_id'=>(int)$match['id'],'room_code'=>$code]);} if($match['status']!=='waiting'||!empty($match['player2_id'])) gd_fail('Stanza non disponibile.'); $mid=(int)$match['id']; $u=$mysqli->prepare("UPDATE game_matches SET player2_id=?,status='team_select',updated_at=NOW() WHERE id=?"); $u->bind_param('ii',$uid,$mid); $u->execute(); $u->close(); $mysqli->commit(); gd_ok(['match_id'=>$mid,'room_code'=>$code]); }
    catch(Throwable $e){ $mysqli->rollback(); if(http_response_code()!==200) exit; error_log('gd_join: '.$e->getMessage()); gd_fail('Join fallito.',500); }
}
function gd_api_inventory(mysqli $mysqli): void {
    $uid=gd_require_login(); $c=gd_char_cols($mysqli); $i=gd_inv_cols($mysqli); if(!$c['id']||!$c['name']||!$i['user']||!$i['character']) gd_fail('Schema inventario non compatibile.',500);
    $fields=['p.'.gd_qcol($c['id']).' id','p.'.gd_qcol($c['name']).' nome']; $fields[]=$c['image']?'p.'.gd_qcol($c['image']).' img_url':"'' img_url"; $fields[]=$c['rarity']?'p.'.gd_qcol($c['rarity']).' rarita':"'comune' rarita"; $fields[]=$c['category']?'p.'.gd_qcol($c['category']).' categoria':"'' categoria"; $fields[]=$i['qty']?'up.'.gd_qcol($i['qty']).' quantita':'1 quantita';
    $sql='SELECT '.implode(',',$fields).' FROM utenti_personaggi up INNER JOIN personaggi p ON p.'.gd_qcol($c['id']).'=up.'.gd_qcol($i['character']).' WHERE up.'.gd_qcol($i['user']).'=? ORDER BY p.'.gd_qcol($c['name']);
    $st=$mysqli->prepare($sql); if(!$st){error_log($mysqli->error.' SQL '.$sql);gd_fail('Query inventario non valida.',500);} $st->bind_param('i',$uid); $st->execute(); $res=$st->get_result(); $cards=[]; while($r=$res->fetch_assoc()){ $s=gd_stats($mysqli,(int)$r['id']); $r['id']=(int)$r['id']; $r['quantita']=(int)($r['quantita']??1); $r['stats']=$s; $cards[]=$r; } $st->close(); gd_ok(['cards'=>$cards]);
}
function gd_api_select_team(mysqli $mysqli): void {
    $uid=gd_require_login(); $in=gd_input(); $mid=(int)($in['match_id']??0); $team=array_values(array_unique(array_map('intval',$in['team']??[]))); if(count($team)!==3) gd_fail('Scegli 3 personaggi diversi.'); $match=gd_require_match($mysqli,$mid,$uid); if(!in_array($match['status'],['waiting','team_select'],true)) gd_fail('Non puoi cambiare team ora.'); if(empty($match['player2_id'])) gd_fail('Aspetta un avversario.'); foreach($team as $pid) if(!gd_owns($mysqli,$uid,$pid)) gd_fail('Hai scelto un personaggio non posseduto.');
    $mysqli->begin_transaction(); try { $q=$mysqli->prepare('DELETE FROM game_match_cards WHERE match_id=? AND user_id=?'); $q->bind_param('ii',$mid,$uid); $q->execute(); $q->close(); $ins=$mysqli->prepare('INSERT INTO game_match_cards (match_id,user_id,personaggio_id,slot_index,current_hp,max_hp,attack,defense,speed,energy,max_energy,special_name,special_cost,special_cooldown_max,special_cooldown,is_active) VALUES (?,?,?,?,?,?,?,?,?,1,?,?,?,?,0,?)'); if(!$ins) throw new Exception($mysqli->error); foreach($team as $idx=>$pid){$s=gd_stats($mysqli,$pid);$slot=$idx+1;$active=$idx===0?1:0;$hp=(int)$s['hp'];$atk=(int)$s['attack'];$def=(int)$s['defense'];$spd=(int)$s['speed'];$en=(int)$s['max_energy'];$name=(string)$s['special_name'];$cost=(int)$s['special_cost'];$cd=(int)$s['special_cooldown'];$ins->bind_param('iiiiiiiiiisiii',$mid,$uid,$pid,$slot,$hp,$hp,$atk,$def,$spd,$en,$name,$cost,$cd,$active);$ins->execute();} $ins->close(); $col=((int)$match['player1_id']===$uid)?'player1_ready':'player2_ready'; $q=$mysqli->prepare("UPDATE game_matches SET $col=1,status='team_select',updated_at=NOW() WHERE id=?"); $q->bind_param('i',$mid); $q->execute(); $q->close(); $mysqli->commit(); gd_start_if_ready($mysqli,$mid); gd_ok(['message'=>'Team scelto.']); } catch(Throwable $e){$mysqli->rollback();error_log('gd_select_team: '.$e->getMessage());gd_fail('Selezione team fallita.',500);} 
}
function gd_api_state(mysqli $mysqli): void { $uid=gd_require_login(); $mid=(int)(gd_input()['match_id'] ?? $_GET['match_id'] ?? 0); $match=gd_match($mysqli,$mid); if(!$match) gd_fail('Partita non trovata.',404); if(!gd_is_player($match,$uid) && (int)$match['spectator_allowed']!==1) gd_fail('Non puoi vedere questa partita.',403); gd_ok(['match'=>gd_state($mysqli,$match,$uid)]); }
function gd_api_action(mysqli $mysqli): void {
    $uid=gd_require_login(); $in=gd_input(); $mid=(int)($in['match_id']??0); $act=(string)($in['action']??''); $target=(int)($in['target_card_id']??0); if(!in_array($act,['basic_attack','special_attack','defend','charge','switch'],true)) gd_fail('Azione non valida.');
    $mysqli->begin_transaction(); try { $st=$mysqli->prepare('SELECT * FROM game_matches WHERE id=? LIMIT 1 FOR UPDATE'); $st->bind_param('i',$mid); $st->execute(); $match=$st->get_result()->fetch_assoc(); $st->close(); if(!$match) gd_fail('Partita non trovata.',404); if(!gd_is_player($match,$uid)) gd_fail('Non fai parte della partita.',403); if($match['status']!=='active') gd_fail('Partita non attiva.'); if((int)$match['current_turn_user_id']!==$uid) gd_fail('Non è il tuo turno.'); $turn=(int)$match['turn_number']; $opp=(int)$match['player1_id']===$uid?(int)$match['player2_id']:(int)$match['player1_id']; $actor=gd_active($mysqli,$mid,$uid); if(!$actor) gd_fail('Nessuna carta attiva.'); $actorId=(int)$actor['id']; $dmg=0; $msg='';
        if($act==='switch'){ $q=$mysqli->prepare('SELECT * FROM game_match_cards WHERE id=? AND match_id=? AND user_id=? AND is_ko=0 LIMIT 1'); $q->bind_param('iii',$target,$mid,$uid); $q->execute(); $new=$q->get_result()->fetch_assoc(); $q->close(); if(!$new) gd_fail('Cambio non valido.'); gd_set_active($mysqli,$mid,$uid,(int)$new['id']); $actorId=(int)$new['id']; $msg='Cambio carta.'; }
        elseif($act==='defend'){ $en=min((int)$actor['max_energy'],(int)$actor['energy']+1); $q=$mysqli->prepare('UPDATE game_match_cards SET is_defending=1, energy=? WHERE id=?'); $q->bind_param('ii',$en,$actorId); $q->execute(); $q->close(); $msg='Difesa attiva.'; }
        elseif($act==='charge'){ $en=min((int)$actor['max_energy'],(int)$actor['energy']+2); $q=$mysqli->prepare('UPDATE game_match_cards SET energy=? WHERE id=?'); $q->bind_param('ii',$en,$actorId); $q->execute(); $q->close(); $msg='Carica energia.'; }
        else { $t=null; if($target>0){$q=$mysqli->prepare('SELECT * FROM game_match_cards WHERE id=? AND match_id=? AND user_id=? AND is_ko=0 LIMIT 1');$q->bind_param('iii',$target,$mid,$opp);$q->execute();$t=$q->get_result()->fetch_assoc();$q->close();} if(!$t) $t=gd_active($mysqli,$mid,$opp); if(!$t) gd_fail('Target non valido.'); $target=(int)$t['id']; if($act==='basic_attack'){ $dmg=max(5,(int)round((int)$actor['attack']-((int)$t['defense']*.45))); $en=min((int)$actor['max_energy'],(int)$actor['energy']+1); $q=$mysqli->prepare('UPDATE game_match_cards SET energy=? WHERE id=?');$q->bind_param('ii',$en,$actorId);$q->execute();$q->close(); $msg='Attacco base.'; } else { if((int)$actor['energy'] < (int)$actor['special_cost']) gd_fail('Energia insufficiente.'); if((int)$actor['special_cooldown']>0) gd_fail('Speciale in cooldown.'); $dmg=max(10,(int)round(((int)$actor['attack']*1.65)-((int)$t['defense']*.35))); $en=max(0,(int)$actor['energy']-(int)$actor['special_cost']); $cd=max(1,(int)$actor['special_cooldown_max']); $q=$mysqli->prepare('UPDATE game_match_cards SET energy=?, special_cooldown=? WHERE id=?');$q->bind_param('iii',$en,$cd,$actorId);$q->execute();$q->close(); $msg=(string)$actor['special_name']; } if((int)$t['is_defending']===1) $dmg=max(2,(int)floor($dmg*.6)); $hp=max(0,(int)$t['current_hp']-$dmg); $ko=$hp<=0?1:0; $q=$mysqli->prepare('UPDATE game_match_cards SET current_hp=?, is_ko=?, is_active=IF(?=1,0,is_active), is_defending=0 WHERE id=?');$q->bind_param('iiii',$hp,$ko,$ko,$target);$q->execute();$q->close(); if($ko){$n=gd_first_alive($mysqli,$mid,$opp); if($n) gd_set_active($mysqli,$mid,$opp,(int)$n['id']);} }
        if($act!=='special_attack'){ $q=$mysqli->prepare('UPDATE game_match_cards SET special_cooldown=GREATEST(0,special_cooldown-1) WHERE match_id=? AND user_id=? AND special_cooldown>0'); $q->bind_param('ii',$mid,$uid); $q->execute(); $q->close(); }
        gd_log($mysqli,$mid,$uid,$turn,$act,$actorId,$target?:null,$dmg,$msg); if(gd_alive_count($mysqli,$mid,$opp)<=0){ gd_finish($mysqli,$match,$uid,$opp); $mysqli->commit(); gd_ok(['finished'=>true,'message'=>'Hai vinto.']); }
        $q=$mysqli->prepare('UPDATE game_matches SET current_turn_user_id=?, turn_number=turn_number+1, updated_at=NOW() WHERE id=?'); $q->bind_param('ii',$opp,$mid); $q->execute(); $q->close(); $mysqli->commit(); gd_ok(['finished'=>false,'message'=>'Azione inviata.']);
    } catch(Throwable $e){ $mysqli->rollback(); if(http_response_code()!==200) exit; error_log('gd_action: '.$e->getMessage()); gd_fail('Azione fallita.',500); }
}
function gd_api_forfeit(mysqli $mysqli): void { $uid=gd_require_login(); $mid=(int)(gd_input()['match_id']??0); $match=gd_require_match($mysqli,$mid,$uid); if(in_array($match['status'],['finished','cancelled'],true)) gd_fail('Partita già conclusa.'); $opp=(int)$match['player1_id']===$uid?(int)$match['player2_id']:(int)$match['player1_id']; if($opp>0){gd_log($mysqli,$mid,$uid,(int)$match['turn_number'],'forfeit',null,null,0,'Abbandona la partita.'); gd_finish($mysqli,$match,$opp,$uid);} else {$q=$mysqli->prepare("UPDATE game_matches SET status='cancelled',finished_at=NOW() WHERE id=?");$q->bind_param('i',$mid);$q->execute();$q->close();} gd_ok(['message'=>'Partita abbandonata.']); }
function gd_api_ranking(mysqli $mysqli): void { gd_require_login(); $q=$mysqli->prepare('SELECT s.*, u.username FROM game_player_stats s INNER JOIN utenti u ON u.id=s.user_id ORDER BY s.rating DESC, s.wins DESC LIMIT 50'); if(!$q) gd_fail('Query ranking non valida.',500); $q->execute(); $res=$q->get_result(); $out=[]; while($r=$res->fetch_assoc()){ $rating=(int)$r['rating']; $out[]=['username'=>$r['username'],'wins'=>(int)$r['wins'],'losses'=>(int)$r['losses'],'rating'=>$rating,'rank'=>gd_rank_from_rating($rating),'season_points'=>(int)$r['season_points'],'best_streak'=>(int)$r['best_streak']];} $q->close(); gd_ok(['ranking'=>$out]); }
function gd_api_active_match(mysqli $mysqli): void { $uid=gd_require_login(); $q=$mysqli->prepare("SELECT id,room_code,status,mode FROM game_matches WHERE (player1_id=? OR player2_id=?) AND status IN ('waiting','team_select','active') ORDER BY updated_at DESC LIMIT 1"); $q->bind_param('ii',$uid,$uid); $q->execute(); $m=$q->get_result()->fetch_assoc(); $q->close(); gd_ok(['match'=>$m ?: null]); }
function gd_api_profile_summary(mysqli $mysqli): void { $uid=gd_require_login(); $u=gd_user_public($mysqli,$uid); $inv=gd_inventory_count($mysqli,$uid); gd_ok(['profile'=>['user'=>$u,'inventory'=>$inv]]); }
