<?php

/**
 * Testi della pagina Posta (messaggi del sito e ticket di supporto).
 *
 * Stanno in un posto solo per le due lingue; la pagina li passa tutti ad
 * assets/inbox/inbox.js, che non ha testi suoi.
 */

if (!function_exists('inbox_strings')) {

    function inbox_strings(string $lang): array
    {
        $strings = [
            'it' => [
                // ── pagina ─────────────────────────────────────────
                'page_title'     => 'Posta',
                'og_description' => 'La tua posta su Cripsum™: comunicazioni del sito, premi da riscattare e ticket di supporto.',
                'sec_messages'   => 'Messaggi',
                'sec_tickets'    => 'Ticket',
                'search'         => 'Cerca nella posta...',
                'search_tickets' => 'Cerca tra i ticket...',
                'more'           => 'Altro',
                'select'         => 'Seleziona',
                'back'           => 'Torna all\'elenco',

                // ── categorie ──────────────────────────────────────
                'cat_all'        => 'Tutti',
                'cat_system'     => 'Sistema',
                'cat_changelog'  => 'Novità',
                'cat_security'   => 'Sicurezza',
                'cat_moderation' => 'Moderazione',
                'cat_social'     => 'Social',
                'cat_rewards'    => 'Premi',
                'cat_special'    => 'Speciali',

                // ── filtri ─────────────────────────────────────────
                'filter'      => 'Filtro',
                'tab_inbox'   => 'In arrivo',
                'tab_unread'  => 'Non letti',
                'tab_starred' => 'Importanti',
                'tab_archive' => 'Archivio',
                'tab_open'    => 'Aperti',
                'tab_closed'  => 'Chiusi',

                // ── elenco ─────────────────────────────────────────
                'load_error'      => 'Non è stato possibile caricare la posta.',
                'retry'           => 'Riprova',
                'load_more'       => 'Carica altri',
                'empty_inbox'     => 'Nessun messaggio',
                'empty_inbox_sub' => 'Comunicazioni del sito, premi e avvisi di sicurezza arrivano qui.',
                'empty_filter'    => 'Niente con questo filtro',
                'empty_filter_sub' => 'Prova a cambiare categoria o a togliere la ricerca.',
                'empty_tickets'   => 'Nessun ticket',
                'empty_tickets_sub' => 'Hai bisogno di una mano? Apri un ticket e lo staff ti risponde qui.',
                'new_ticket'      => 'Apri un ticket',
                'welcome_title'   => 'Scegli un messaggio',
                'welcome_sub'     => 'Selezionalo dall\'elenco per leggerlo. I ticket di supporto stanno nella seconda scheda.',

                // ── azioni ─────────────────────────────────────────
                'star'           => 'Segna come importante',
                'unstar'         => 'Togli da importanti',
                'archive'        => 'Archivia',
                'restore'        => 'Ripristina',
                'delete'         => 'Elimina',
                'mark_unread'    => 'Segna come da leggere',
                'mark_read'      => 'Segna come letti',
                'read_all'       => 'Segna tutto come letto',
                'claim_all'      => 'Riscatta tutti i premi',
                'alerts'         => 'Avvisi e suoni',
                'previous'       => 'Più recente',
                'next'           => 'Più vecchio',
                'archived_done'  => 'Messaggio archiviato.',
                'restored_done'  => 'Messaggio ripristinato.',
                'undo'           => 'Annulla',
                'delete_title'   => 'Eliminare il messaggio?',
                'delete_text'    => 'Sparisce dalla tua posta e non si può recuperare.',
                'delete_many_title' => 'Eliminare i messaggi selezionati?',
                'selected'       => '{n} selezionati',
                'read_all_done'  => 'Tutto letto.',
                'nothing_to_claim' => 'Non ci sono premi da riscattare.',

                // ── premi ──────────────────────────────────────────
                'rewards_included'     => 'Premi in questo messaggio',
                'rewards_claimed'      => 'Premi riscattati',
                'claim_rewards'        => 'Riscatta i premi',
                'claimed_title'        => 'Premi riscattati!',
                'claimed_sub'          => 'Sono già sul tuo account:',
                'claimed_close'        => 'Ottimo',
                'reward_money_sub'     => 'Valuta del sito',
                'reward_shard_sub'     => 'Valuta rara del sito',
                'reward_character'     => 'Personaggio',
                'reward_character_sub' => 'Aggiunto all\'inventario',
                'reward_badge'         => 'Badge',
                'reward_badge_sub'     => 'Sbloccato sul profilo',
                'reward_premium'       => 'Premium',
                'reward_premium_sub'   => 'Vantaggi Premium attivati',

                // ── ticket ─────────────────────────────────────────
                'topic'                => 'Argomento',
                'user'                 => 'Utente',
                'guest'                => 'Ospite',
                'staff'                => 'Staff',
                'status_open'          => 'Aperto',
                'status_closed'        => 'Chiuso',
                'ticket_reopen'        => 'Riapri',
                'ticket_close'         => 'Chiudi ticket',
                'ticket_close_title'   => 'Chiudere il ticket?',
                'ticket_close_text'    => 'L\'utente non potrà più rispondere finché non lo riapri. Su Discord il thread viene avvisato.',
                'ticket_closed_banner' => 'Questo ticket è chiuso. Per altro, apri un nuovo ticket.',
                'ticket_closed_staff'  => 'Questo ticket è chiuso. Riaprilo per rispondere.',
                'ticket_on_discord'    => 'Collegato a un thread Discord',
                'ticket_from_discord'  => 'Aperto da Discord',
                'reply_placeholder'    => 'Rispondi al ticket...',
                'no_chat_messages'     => 'Ancora nessun messaggio.',
                'only_images'          => 'Ai ticket si possono allegare solo immagini.',
                'image_too_big'        => 'L\'immagine non può superare i 5 MB.',
                'image_label'          => 'Immagine',
            ],

            'en' => [
                'page_title'     => 'Inbox',
                'og_description' => 'Your Cripsum™ inbox: site announcements, rewards to claim and support tickets.',
                'sec_messages'   => 'Messages',
                'sec_tickets'    => 'Tickets',
                'search'         => 'Search your inbox...',
                'search_tickets' => 'Search tickets...',
                'more'           => 'More',
                'select'         => 'Select',
                'back'           => 'Back to the list',

                'cat_all'        => 'All',
                'cat_system'     => 'System',
                'cat_changelog'  => 'Changelog',
                'cat_security'   => 'Security',
                'cat_moderation' => 'Moderation',
                'cat_social'     => 'Social',
                'cat_rewards'    => 'Rewards',
                'cat_special'    => 'Special',

                'filter'      => 'Filter',
                'tab_inbox'   => 'Inbox',
                'tab_unread'  => 'Unread',
                'tab_starred' => 'Starred',
                'tab_archive' => 'Archive',
                'tab_open'    => 'Open',
                'tab_closed'  => 'Closed',

                'load_error'      => 'The inbox could not be loaded.',
                'retry'           => 'Retry',
                'load_more'       => 'Load more',
                'empty_inbox'     => 'No messages',
                'empty_inbox_sub' => 'Site announcements, rewards and security alerts arrive here.',
                'empty_filter'    => 'Nothing with this filter',
                'empty_filter_sub' => 'Try another category or clear the search.',
                'empty_tickets'   => 'No tickets',
                'empty_tickets_sub' => 'Need a hand? Open a ticket and the staff will answer here.',
                'new_ticket'      => 'Open a ticket',
                'welcome_title'   => 'Pick a message',
                'welcome_sub'     => 'Select it from the list to read it. Support tickets live in the second tab.',

                'star'           => 'Mark as important',
                'unstar'         => 'Remove from important',
                'archive'        => 'Archive',
                'restore'        => 'Restore',
                'delete'         => 'Delete',
                'mark_unread'    => 'Mark as unread',
                'mark_read'      => 'Mark as read',
                'read_all'       => 'Mark all as read',
                'claim_all'      => 'Claim all rewards',
                'alerts'         => 'Alerts and sounds',
                'previous'       => 'Newer',
                'next'           => 'Older',
                'archived_done'  => 'Message archived.',
                'restored_done'  => 'Message restored.',
                'undo'           => 'Undo',
                'delete_title'   => 'Delete this message?',
                'delete_text'    => 'It disappears from your inbox and cannot be recovered.',
                'delete_many_title' => 'Delete the selected messages?',
                'selected'       => '{n} selected',
                'read_all_done'  => 'All read.',
                'nothing_to_claim' => 'There are no rewards to claim.',

                'rewards_included'     => 'Rewards in this message',
                'rewards_claimed'      => 'Rewards claimed',
                'claim_rewards'        => 'Claim rewards',
                'claimed_title'        => 'Rewards claimed!',
                'claimed_sub'          => 'They are already on your account:',
                'claimed_close'        => 'Great',
                'reward_money_sub'     => 'Site currency',
                'reward_shard_sub'     => 'Rare site currency',
                'reward_character'     => 'Character',
                'reward_character_sub' => 'Added to your inventory',
                'reward_badge'         => 'Badge',
                'reward_badge_sub'     => 'Unlocked on your profile',
                'reward_premium'       => 'Premium',
                'reward_premium_sub'   => 'Premium perks activated',

                'topic'                => 'Topic',
                'user'                 => 'User',
                'guest'                => 'Guest',
                'staff'                => 'Staff',
                'status_open'          => 'Open',
                'status_closed'        => 'Closed',
                'ticket_reopen'        => 'Reopen',
                'ticket_close'         => 'Close ticket',
                'ticket_close_title'   => 'Close this ticket?',
                'ticket_close_text'    => 'The user will not be able to reply until you reopen it. The Discord thread is notified.',
                'ticket_closed_banner' => 'This ticket is closed. For anything else, open a new ticket.',
                'ticket_closed_staff'  => 'This ticket is closed. Reopen it to reply.',
                'ticket_on_discord'    => 'Linked to a Discord thread',
                'ticket_from_discord'  => 'Opened from Discord',
                'reply_placeholder'    => 'Reply to the ticket...',
                'no_chat_messages'     => 'No messages yet.',
                'only_images'          => 'Only images can be attached to tickets.',
                'image_too_big'        => 'The image cannot exceed 5 MB.',
                'image_label'          => 'Image',
            ],
        ];

        return $strings[$lang] ?? $strings['it'];
    }
}
