<?php

/**
 * Testi dell'interfaccia di Shitpost e Top Rimasti, nelle due lingue.
 *
 * Le chiavi che finiscono con il nome della sezione (`title_shitpost`,
 * `title_rimasto`) cambiano fra le due pagine; cm_strings() restituisce già
 * quella giusta sotto la chiave corta (`title`).
 */
function cm_strings(string $lang, string $type): array
{
    $all = [
        'it' => [
            // Testata
            'title_shitpost' => 'Shitpost',
            'title_rimasto' => 'Top Rimasti',
            'subtitle_shitpost' => 'Meme, GIF e video della community.',
            'subtitle_rimasto' => 'La classifica dei più rimasti, decisa dai voti della community.',
            'new_shitpost' => 'Nuovo shitpost',
            'new_rimasto' => 'Candida un rimasto',
            'login_to_post' => 'Accedi per pubblicare',
            'closed' => 'Pubblicazioni chiuse',

            // Barra
            'sort_recent' => 'Recenti',
            'sort_trending' => 'In tendenza',
            'sort_top' => 'Più votati',
            'sort_comments' => 'Più commentati',
            'rank_all' => 'Di sempre',
            'rank_month' => 'Questo mese',
            'rank_week' => 'Questa settimana',
            'rank_new' => 'Nuovi arrivi',
            'sort_label' => 'Ordina i post',
            'search_shitpost' => 'Cerca titolo, autore o tag',
            'search_rimasto' => 'Cerca un rimasto',
            'search_clear' => 'Pulisci la ricerca',
            'saved' => 'Salvati',
            'mine' => 'I miei',
            'pending_filter' => 'In attesa',
            'all_tags' => 'Tutti',
            'new_posts_one' => '1 nuovo post',
            'new_posts_many' => '%d nuovi post',

            // Card
            'open_post' => 'Apri il post',
            'untitled' => 'Senza titolo',
            'deleted_user' => 'utente eliminato',
            'pending_own' => 'In attesa di approvazione · lo vedi solo tu',
            'pending_staff' => 'In attesa di approvazione',
            'spoiler' => 'Spoiler',
            'spoiler_hint' => 'Tocca per vedere',
            'media_count' => '%d media',
            'react' => 'Reagisci',
            'reactions' => 'Reazioni',
            'comments' => 'Commenti',
            'save' => 'Salva',
            'unsave' => 'Togli dai salvati',
            'share' => 'Condividi',
            'more' => 'Altre azioni',
            'vote' => 'Vota',
            'voted' => 'Votato',
            'votes' => 'voti',
            'vote_one' => 'voto',
            'views' => 'visite',

            // Menu
            'copy_link' => 'Copia link',
            'report' => 'Segnala',
            'edit' => 'Modifica',
            'delete' => 'Elimina',
            'approve' => 'Approva',
            'hide' => 'Nascondi',

            // Tempo
            'now' => 'adesso',

            // Stati vuoti
            'empty_title' => 'Ancora niente qui',
            'empty_text' => 'Quando qualcuno pubblica, lo trovi in questa pagina.',
            'empty_search_title' => 'Nessun risultato',
            'empty_search_text' => 'Prova con altre parole o togli i filtri.',
            'empty_saved_title' => 'Non hai salvato niente',
            'empty_saved_text' => 'Tocca il segnalibro su un post per ritrovarlo qui.',
            'empty_mine_title' => 'Non hai ancora pubblicato',
            'empty_mine_text' => 'I tuoi post, anche quelli in attesa, compaiono qui.',
            'empty_period_title' => 'Nessun voto in questo periodo',
            'empty_period_text' => 'Vota un rimasto e la classifica prende vita.',
            'empty_pending_title' => 'Niente da approvare',
            'empty_pending_text' => 'La coda è vuota.',
            'reset_filters' => 'Togli i filtri',
            'load_error' => 'Non sono riuscito a caricare i post.',
            'retry' => 'Riprova',
            'post_gone' => 'Questo post non è più disponibile.',
            'hall_title' => 'Albo d\'oro',
            'hall_text' => 'Il più votato di ogni mese',

            // Post aperto
            'close' => 'Chiudi',
            'prev' => 'Precedente',
            'next' => 'Successivo',
            'zoom' => 'Ingrandisci',
            'fullscreen' => 'Schermo intero',
            'motivation' => 'Motivazione',
            'comments_none' => 'Nessun commento. Scrivi il primo.',
            'comments_count_one' => '1 commento',
            'comments_count_many' => '%d commenti',
            'comment_placeholder' => 'Scrivi un commento…',
            'comment_login' => 'Accedi per commentare',
            'comment_send' => 'Invia il commento',
            'comment_pending' => 'Si potrà commentare quando il post sarà online.',
            'reply' => 'Rispondi',
            'replying_to' => 'Risposta a @%s',
            'cancel_reply' => 'Annulla la risposta',
            'confirm_short' => 'Sicuro?',
            'comment_deleted' => 'Commento eliminato.',

            // Avvisi
            'must_login' => 'Devi accedere.',
            'link_copied' => 'Link copiato.',
            'copy_failed' => 'Non sono riuscito a copiare il link.',
            'saved_done' => 'Salvato.',
            'unsaved_done' => 'Tolto dai salvati.',
            'network_error' => 'Connessione assente o server non raggiungibile.',

            // Nuovo post / modifica
            'composer_hint' => 'Trascina i file, incollali con Ctrl+V o sceglili dal dispositivo.',
            'composer_edit_title' => 'Modifica il post',
            'composer_edit_hint' => 'Puoi cambiare testo, tag e spoiler. I file restano quelli.',
            'composer_review_note' => 'Se cambi titolo o testo il post torna in attesa di approvazione.',
            'drop_title' => 'Aggiungi immagini, GIF o video',
            'drop_text' => 'Fino a %d file',
            'drop_text_one' => 'Un file per post',
            'drop_limits' => 'JPG, PNG, GIF, WEBP fino a 8 MB · MP4, WEBM fino a 20 MB.',
            'drop_privacy' => 'Posizione e dati della fotocamera vengono tolti dalle foto.',
            'add_more' => 'Aggiungi',
            'cover' => 'Copertina',
            'remove_file' => 'Togli il file',
            'move_left' => 'Sposta prima',
            'move_right' => 'Sposta dopo',
            'field_title' => 'Titolo',
            'field_title_ph' => 'Un titolo breve',
            'field_description' => 'Descrizione',
            'field_description_ph' => 'Un po\' di contesto, se serve',
            'field_motivation' => 'Motivazione',
            'field_motivation_ph' => 'Perché merita di stare in classifica?',
            'optional' => 'facoltativa',
            'field_tags' => 'Tag',
            'field_tags_hint' => 'fino a 3',
            'field_tags_ph' => 'aggiungi…',
            'field_spoiler' => 'Spoiler',
            'field_spoiler_hint' => 'Il post resta sfocato finché non lo si tocca.',
            'review_note' => 'Ogni post viene controllato prima di apparire. Ti avvisiamo nella campanella quando è online.',
            'review_note_auto' => 'Il tuo post va online subito.',
            'cancel' => 'Annulla',
            'publish' => 'Pubblica',
            'save_changes' => 'Salva',
            'uploading' => 'Caricamento %d%%',
            'sending' => 'Invio…',
            'err_type' => 'Formato non supportato: usa JPG, PNG, GIF, WEBP, MP4 o WEBM.',
            'err_image_size' => 'Immagine troppo grande: massimo 8 MB.',
            'err_video_size' => 'Video troppo grande: massimo 20 MB.',
            'err_too_many' => 'Puoi caricare al massimo %d file per post.',
            'err_no_media' => 'Aggiungi almeno un\'immagine o un video.',
            'err_upload_wait' => 'Aspetta che i file finiscano di caricarsi.',
            'err_upload_failed' => 'Un file non è stato caricato: toglilo o riprova.',
            'err_title' => 'Scrivi un titolo.',
            'err_motivation' => 'Scrivi la motivazione.',
            'upload_retry' => 'Riprova',
            'created_pending' => 'Inviato. Lo trovi in «I miei» finché non viene approvato.',
            'created_live' => 'Pubblicato.',
            'discard_title' => 'Uscire senza pubblicare?',
            'discard_text' => 'Quello che hai scritto e caricato andrà perso.',
            'discard_confirm' => 'Esci',
            'discard_stay' => 'Resta',

            // Segnala
            'report_title' => 'Segnala il post',
            'report_hint' => 'Lo staff lo controlla il prima possibile.',
            'report_detail' => 'Dettagli (facoltativi)',
            'report_detail_ph' => 'Aggiungi qualcosa che ci aiuti a capire',
            'report_send' => 'Invia segnalazione',
            'report_reason_nsfw' => 'Contenuto inappropriato o nudità',
            'report_reason_spam' => 'Spam o pubblicità',
            'report_reason_hate' => 'Odio, molestie o bullismo',
            'report_reason_rules' => 'Viola il regolamento',
            'report_reason_other' => 'Altro',

            // Conferme
            'delete_title' => 'Eliminare il post?',
            'delete_text' => 'Spariscono anche commenti, reazioni e voti. Non si può annullare.',
            'delete_reason' => 'Motivo (arriva all\'autore)',
            'delete_reason_none' => 'Nessun motivo',
            'delete_reason_other' => 'Altro…',
            'delete_reason_ph' => 'Scrivi il motivo',
            'reason_duplicate' => 'Doppione',
            'reason_quality' => 'Bassa qualità',
            'reason_offtopic' => 'Fuori tema',
            'reason_rules' => 'Contenuto vietato',
            'hide_title' => 'Nascondere il post?',
            'hide_text' => 'Torna in attesa: non lo vede più nessuno finché non lo riapprovi.',
        ],

        'en' => [
            'title_shitpost' => 'Shitpost',
            'title_rimasto' => 'Top Braindeads',
            'subtitle_shitpost' => 'Memes, GIFs and videos from the community.',
            'subtitle_rimasto' => 'The ranking of the most braindead moments, decided by community votes.',
            'new_shitpost' => 'New shitpost',
            'new_rimasto' => 'Add a Braindead',
            'login_to_post' => 'Log in to post',
            'closed' => 'Posting is closed',

            'sort_recent' => 'Recent',
            'sort_trending' => 'Trending',
            'sort_top' => 'Most voted',
            'sort_comments' => 'Most commented',
            'rank_all' => 'All time',
            'rank_month' => 'This month',
            'rank_week' => 'This week',
            'rank_new' => 'New entries',
            'sort_label' => 'Sort posts',
            'search_shitpost' => 'Search title, author or tag',
            'search_rimasto' => 'Search a braindead',
            'search_clear' => 'Clear search',
            'saved' => 'Saved',
            'mine' => 'Mine',
            'pending_filter' => 'Pending',
            'all_tags' => 'All',
            'new_posts_one' => '1 new post',
            'new_posts_many' => '%d new posts',

            'open_post' => 'Open the post',
            'untitled' => 'Untitled',
            'deleted_user' => 'deleted user',
            'pending_own' => 'Waiting for approval · only you can see it',
            'pending_staff' => 'Waiting for approval',
            'spoiler' => 'Spoiler',
            'spoiler_hint' => 'Tap to reveal',
            'media_count' => '%d media',
            'react' => 'React',
            'reactions' => 'Reactions',
            'comments' => 'Comments',
            'save' => 'Save',
            'unsave' => 'Remove from saved',
            'share' => 'Share',
            'more' => 'More actions',
            'vote' => 'Vote',
            'voted' => 'Voted',
            'votes' => 'votes',
            'vote_one' => 'vote',
            'views' => 'views',

            'copy_link' => 'Copy link',
            'report' => 'Report',
            'edit' => 'Edit',
            'delete' => 'Delete',
            'approve' => 'Approve',
            'hide' => 'Hide',

            'now' => 'now',

            'empty_title' => 'Nothing here yet',
            'empty_text' => 'When someone posts, you will find it on this page.',
            'empty_search_title' => 'No results',
            'empty_search_text' => 'Try other words or remove the filters.',
            'empty_saved_title' => 'You have not saved anything',
            'empty_saved_text' => 'Tap the bookmark on a post to find it here.',
            'empty_mine_title' => 'You have not posted yet',
            'empty_mine_text' => 'Your posts, including the ones in review, show up here.',
            'empty_period_title' => 'No votes in this period',
            'empty_period_text' => 'Vote a post and the ranking comes alive.',
            'empty_pending_title' => 'Nothing to approve',
            'empty_pending_text' => 'The queue is empty.',
            'reset_filters' => 'Remove filters',
            'load_error' => 'I could not load the posts.',
            'retry' => 'Try again',
            'post_gone' => 'This post is no longer available.',
            'hall_title' => 'Hall of fame',
            'hall_text' => 'The most voted of each month',

            'close' => 'Close',
            'prev' => 'Previous',
            'next' => 'Next',
            'zoom' => 'Zoom in',
            'fullscreen' => 'Full screen',
            'motivation' => 'Motivation',
            'comments_none' => 'No comments. Write the first one.',
            'comments_count_one' => '1 comment',
            'comments_count_many' => '%d comments',
            'comment_placeholder' => 'Write a comment…',
            'comment_login' => 'Log in to comment',
            'comment_send' => 'Send the comment',
            'comment_pending' => 'Comments open when the post is online.',
            'reply' => 'Reply',
            'replying_to' => 'Replying to @%s',
            'cancel_reply' => 'Cancel the reply',
            'confirm_short' => 'Sure?',
            'comment_deleted' => 'Comment deleted.',

            'must_login' => 'You need to log in.',
            'link_copied' => 'Link copied.',
            'copy_failed' => 'I could not copy the link.',
            'saved_done' => 'Saved.',
            'unsaved_done' => 'Removed from saved.',
            'network_error' => 'No connection or server unreachable.',

            'composer_hint' => 'Drag files in, paste them with Ctrl+V or pick them from your device.',
            'composer_edit_title' => 'Edit the post',
            'composer_edit_hint' => 'You can change text, tags and spoiler. The files stay as they are.',
            'composer_review_note' => 'If you change the title or the text the post goes back to review.',
            'drop_title' => 'Add images, GIFs or videos',
            'drop_text' => 'Up to %d files',
            'drop_text_one' => 'One file per post',
            'drop_limits' => 'JPG, PNG, GIF, WEBP up to 8 MB · MP4, WEBM up to 20 MB.',
            'drop_privacy' => 'Location and camera data are removed from photos.',
            'add_more' => 'Add',
            'cover' => 'Cover',
            'remove_file' => 'Remove the file',
            'move_left' => 'Move earlier',
            'move_right' => 'Move later',
            'field_title' => 'Title',
            'field_title_ph' => 'A short title',
            'field_description' => 'Description',
            'field_description_ph' => 'Some context, if needed',
            'field_motivation' => 'Motivation',
            'field_motivation_ph' => 'Why does it deserve a place in the ranking?',
            'optional' => 'optional',
            'field_tags' => 'Tags',
            'field_tags_hint' => 'up to 3',
            'field_tags_ph' => 'add…',
            'field_spoiler' => 'Spoiler',
            'field_spoiler_hint' => 'The post stays blurred until it is tapped.',
            'review_note' => 'Every post is checked before it shows up. We let you know in the bell when it is live.',
            'review_note_auto' => 'Your post goes live right away.',
            'cancel' => 'Cancel',
            'publish' => 'Post',
            'save_changes' => 'Save',
            'uploading' => 'Uploading %d%%',
            'sending' => 'Sending…',
            'err_type' => 'Unsupported format: use JPG, PNG, GIF, WEBP, MP4 or WEBM.',
            'err_image_size' => 'Image too large: 8 MB at most.',
            'err_video_size' => 'Video too large: 20 MB at most.',
            'err_too_many' => 'You can upload up to %d files per post.',
            'err_no_media' => 'Add at least one image or video.',
            'err_upload_wait' => 'Wait for the files to finish uploading.',
            'err_upload_failed' => 'A file was not uploaded: remove it or try again.',
            'err_title' => 'Write a title.',
            'err_motivation' => 'Write the motivation.',
            'upload_retry' => 'Try again',
            'created_pending' => 'Sent. You will find it under "Mine" until it is approved.',
            'created_live' => 'Posted.',
            'discard_title' => 'Leave without posting?',
            'discard_text' => 'What you wrote and uploaded will be lost.',
            'discard_confirm' => 'Leave',
            'discard_stay' => 'Stay',

            'report_title' => 'Report the post',
            'report_hint' => 'The staff will check it as soon as possible.',
            'report_detail' => 'Details (optional)',
            'report_detail_ph' => 'Add anything that helps us understand',
            'report_send' => 'Send report',
            'report_reason_nsfw' => 'Inappropriate content or nudity',
            'report_reason_spam' => 'Spam or advertising',
            'report_reason_hate' => 'Hate, harassment or bullying',
            'report_reason_rules' => 'Breaks the rules',
            'report_reason_other' => 'Other',

            'delete_title' => 'Delete the post?',
            'delete_text' => 'Comments, reactions and votes go with it. This cannot be undone.',
            'delete_reason' => 'Reason (sent to the author)',
            'delete_reason_none' => 'No reason',
            'delete_reason_other' => 'Other…',
            'delete_reason_ph' => 'Write the reason',
            'reason_duplicate' => 'Duplicate',
            'reason_quality' => 'Low quality',
            'reason_offtopic' => 'Off topic',
            'reason_rules' => 'Forbidden content',
            'hide_title' => 'Hide the post?',
            'hide_text' => 'It goes back to review: nobody sees it until you approve it again.',
        ],
    ];

    $strings = $all[$lang === 'en' ? 'en' : 'it'];
    $suffix = $type === 'rimasto' ? 'rimasto' : 'shitpost';

    foreach (['title', 'subtitle', 'new', 'search'] as $key) {
        $strings[$key] = $strings[$key . '_' . $suffix];
    }

    return $strings;
}
